### ISSUE TITLE
Error: could not connect to sbot

### ISSUE THREAD

**Issue by vtexier** [fraction/ssb-blob-prune#2]
Tried the command on Ubuntu 18.04 64bits.

Node.js v14.1.0 fresh install with `nvm`:

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
```
Restarted shell.

```bash
nvm install node
```
Then...

```bash
npx ssb-blob-prune
```
Tried once with `Patchwork` running. Then, with `Patchwork` not running. Same error.

Here's the console logs:

```bash
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:74: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/config.guess'
configure.ac:9: installing 'build-aux/config.sub'
configure.ac:10: installing 'build-aux/install-sh'
configure.ac:10: installing 'build-aux/missing'
src/libsodium/Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: Leaving directory `.'
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
In file included from ../src/crypto_pwhash_async.cc:2:0,
                 from ../binding.cc:12:
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE sodium_malloc(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   if (((uint64_t) var) < min) { \
../binding.cc:49:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
   ASSERT_UINT_BOUNDS(info[0], size, 0, 0, `buffer.constants.MAX_LENGTH`, node::Buffer::kMaxLength)
   ^~~~~~~~~~~~~~~~~~
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE randombytes_uniform(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   if (((uint64_t) var) < min) { \
../binding.cc:95:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
   ASSERT_UINT_BOUNDS(info[0], upper_bound, 0, 0, 0xffffffff, 0xffffffff)
   ^~~~~~~~~~~~~~~~~~
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE sodium_pad(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   if (((uint64_t) var) < min) { \
../binding.cc:157:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
   ASSERT_UINT_BOUNDS(info[1], unpadded_buflen, 0, 0, `buf.length`, buf_length)
   ^~~~~~~~~~~~~~~~~~
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE sodium_unpad(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   if (((uint64_t) var) < min) { \
../binding.cc:169:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
   ASSERT_UINT_BOUNDS(info[1], padded_buflen, 0, 0, `buf.length`, buf_length)
   ^~~~~~~~~~~~~~~~~~
../src/crypto_generichash_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE CryptoGenericHashWrap::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/crypto_generichash_wrap.cc:11:58: warning: ‘new’ of type ‘CryptoGenericHashWrap’ with extended alignment 64 [-Waligned-new=]
   CryptoGenericHashWrap* obj = new CryptoGenericHashWrap();
                                                          ^
../src/crypto_generichash_wrap.cc:11:58: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
../src/crypto_generichash_wrap.cc:11:58: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
  ssb-blob-prune could not connect to sbot, please ensure that it's running +0ms
/home/vit/.npm/_npx/522/lib/node_modules/ssb-blob-prune/index.js:23
    throw err
    ^

Error: could not connect to sbot
    at /home/vit/.npm/_npx/522/lib/node_modules/ssb-blob-prune/node_modules/ssb-client/client.js:55:17
    at /home/vit/.npm/_npx/522/lib/node_modules/ssb-blob-prune/node_modules/multiserver/compose.js:80:24
    at Socket.<anonymous> (/home/vit/.npm/_npx/522/lib/node_modules/ssb-blob-prune/node_modules/multiserver/plugins/net.js:85:11)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
  Error: connect ECONNREFUSED 127.0.0.1:8008
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
```

**Comment by timjrobinson** [comment]
I just tried this out and it's working for me with patchwork open. If you run `netstat -tulpn | grep 8008` does it show anything running on that port? 

Do you have [ssb-server](https://github.com/ssbc/ssb-server) installed globally? If so can you run `ssb-server whoami` and does that work?

**Comment by vtexier** [comment]
Thanks for your help!

My laptop work only as a ssb client with Patchwork.
The hard disk is full because of the size of the ssb directory. So I was searching for a way to delete useless feeds or better, non read old posts.

I am using this tool to do exactly that, prune my ssb folder. 

    sudo netstat -tulpn | grep 8008

return nothing as expected (no server on my laptop).

Does this tool need to have an ssb server installed? (which would be a little overkill only for cleanup an ssb client hard disk :wink:  )

**Comment by timjrobinson** [comment]
ssb-server should be launched automatically when you run Patchwork, I don't know how Patchwork is working without it. Maybe you changed some configuration to make it run on a different port? 

Could you try `sudo netstat -tulpn | grep asar` while patchwork is running and see if that shows anything, that should help you figure out what port the server is running on.

**Comment by vtexier** [comment]
This time it's a success!

```javascript
  ssb-blob-prune connected to sbot +0ms
  ssb-blob-prune previous total: 51228 +4m
  ssb-blob-prune deleted: 5350 +5ms
  ssb-blob-prune current total: 45878 +0ms
```
Patchwork need to be running to have the ssb-server running...

Many thanks, I close the issue.
